server {
  listen 127.0.0.1:8080;
  server_name _;
  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:js|css|jpg|jpeg|png|webp|avif|svg|woff2|mp4|webm)$ {
    expires 30d;
    add_header Cache-Control "public, immutable";
    try_files $uri /index.html;
  }
}
